### ISSUE TITLE
Please explain this bit 

### ISSUE THREAD

**Issue by idibidiart** [corbt/next-frame#1]
In Readme,

```
let recordingsJSON = await response.json();

for (let recording of recordingsJSON) {
... }
```

Isn't recordingsJSON just a plain object at this point? How is it iterable with for...of ?

Maybe use something like: Object.entries(recordingsJSON)

**Comment by corbt** [comment]
Yeah, the idea is just that recordingJSON is an iterable array (if it were an object then Object.entries would accomplish the same thing). I've clarified the example a bit to hopefully make that more obvious. Thanks for the question.
