### ISSUE TITLE
Rendering a collection of components one frame at a time.

### ISSUE THREAD

**Issue by sbefort** [corbt/next-frame#3]
What if you have an array of objects and want to map through the array, then use the object properties as component props so that each component renders one frame at a time?  Is that possible with this module?  It seems that I can manipulate data with this module one frame at a time, but rendering a component one frame at a time would not work.  Please correct me if I'm wrong.

The issue I have is that once a TouchableOpacity is clicked to render all these components, the rendering makes the TouchableOpacity animation really slow.  So I would like to split up the rendering of these components over multiple frames.

**Comment by corbt** [comment]
Yes, this module doesn't do that. It would be a cool higher-order-component
to create though!

**Comment by sbefort** [comment]
No worries, I think I have an alternative solution.  Thanks!
