### ISSUE TITLE
Why not InteractionManager.runAfterInteractions?

### ISSUE THREAD

**Issue by EgidioCaprino** [corbt/next-frame#6]
Hi @corbt 👋

I like your idea, but I have a question.

Why is your logic based on `requestAnimationFrame` rather than `InteractionManager.runAfterInteractions`. [React Native doc](https://facebook.github.io/react-native/docs/timers) says

> requestAnimationFrame(): for code that animates a view over time.
> runAfterInteractions(): run code later, without delaying active animations.

**Comment by corbt** [comment]
Fair point! I don’t recall whether that callback was available when I wrote
this library, but in many cases that may be the more appropriate choice.
